#!/bin/bash

version=${2:-1}
datafile="data/$1.dta"
logfile="output/$1$version.log"
resultsfile="output/$1$version.out"
savefile="output/$1$version"

rm -f ${logfile}
rm -f ${resultsfile}
rm -f model/pbutterMainSimple.oxo #model/pbutterSimple.oxo model/Inventory.oxo

oxl  -c model/pbutterMainSimple.ox model/pbutterSimple.h model/Inventory.h
#oxl -DVHIGH+LINEAR+COMPLEX -c model/pbutterMainSimple.ox model/pbutterSimple.h model/Inventory.h
mv pbutterMainSimple.oxo model/.

cmd="sqsub -r 6.0h -o ${logfile} -q serial --memperproc=3.5G
 oxl model/pbutterMainSimple.oxo ${datafile} ${logfile} ${resultsfile} ${savefile}"
echo "Starting Peanut Butter Estimation"
echo $cmd

eval $cmd
