#!/bin/bash

version=${2:-1}
datafile="data/$1.dta"
logfile="output/$1$version.log"
resultsfile="output/$1$version.out"
savefile="output/$1$version"

rm -f ${logfile}
rm -f ${resultsfile}
rm -f model/main.oxo
oxl -c model/pbutterMain.ox model/Inventory.h model/pbutter.h
mv pbutterMain.oxo model/.

cmd="sqsub -r 5.0d -o ${logfile} -q serial --memperproc=2.5G
 oxl model/pbutterMain.oxo ${datafile} ${logfile} ${resultsfile} ${savefile}"
echo "Starting Peanut Butter Estimation"
echo $cmd

eval $cmd
