#!/bin/bash

rm -f out.log
rm -f model/main.oxo
oxl -c model/pbutterMain.ox model/Inventory.h model/pbutter.h
mv pbutterMain.oxo model/.

echo $OXHOME

echo "Starting Detergent Estimation"
sqsub -r 8.0h -o out.log -q serial --memperproc=3.5G oxl model/pbutterMain.oxo
