#!/bin/bash

logfile = ${1:-out.log}

rm -f out.log
rm -f model/main.oxo
oxl -c model/pbutterMain.ox model/Inventory.h model/pbutter.h
mv pbutterMain.oxo model/.

echo $OXHOME

echo "Starting Detergent Estimation"
sqsub -r 6.0h -o ${logfile} -q serial --memperproc=3.5G oxl model/pbutterMain.oxo
