#!/bin/bash

rm -f out.log
rm -f model/main.oxo
oxl -c model/pbutterMain.ox model/Inventory.h model/pbutter.h
mv pbutterMain.oxo model/pbutterStage1.oxo

echo $OXHOME

echo "Starting Detergent Estimation"
sqsub -r 24.0h -o out.log -q serial --memperproc=3.5G oxl model/pbutterStage1.oxo
